spring.application.name=ai-billing-intelligence

spring.datasource.url=jdbc:h2:mem:billingdb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.port=8080

billing.ai.mode=auto
billing.ai.openai.api-key=${OPENAI_API_KEY:}
billing.ai.openai.model=gpt-4o-mini
billing.ai.openai.base-url=https://api.openai.com/v1

logging.level.com.capstone.billing=INFO
