-- AI Billing Intelligence — Oracle schema (12c+ identity columns)
-- Run before seed-data.sql when provisioning Oracle manually.

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ai_decisions CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE payment_history CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE claims CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE policies CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE customers CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE customers (
    id                          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                        VARCHAR2(120) NOT NULL,
    age                         NUMBER(3),
    occupation                  VARCHAR2(80),
    income_segment              VARCHAR2(20),
    region                      VARCHAR2(80),
    preferred_payment_method    VARCHAR2(20),
    salary_credit_day           NUMBER(2)
);

CREATE TABLE policies (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_number   VARCHAR2(40) NOT NULL UNIQUE,
    policy_type     VARCHAR2(20),
    premium         NUMBER(12, 2) NOT NULL,
    due_date        DATE,
    auto_pay        NUMBER(1) DEFAULT 0 NOT NULL,
    status          VARCHAR2(20),
    risk_score      NUMBER(3),
    customer_id     NUMBER NOT NULL,
    CONSTRAINT fk_policies_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE TABLE claims (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id    NUMBER NOT NULL,
    amount       NUMBER(12, 2) NOT NULL,
    status       VARCHAR2(20),
    claim_date   DATE,
    description  VARCHAR2(255),
    CONSTRAINT fk_claims_policy FOREIGN KEY (policy_id) REFERENCES policies (id)
);

CREATE TABLE payment_history (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id  NUMBER NOT NULL,
    due_date   DATE,
    paid_date  DATE,
    amount     NUMBER(12, 2) NOT NULL,
    missed     NUMBER(1) DEFAULT 0 NOT NULL,
    late       NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_payment_history_policy FOREIGN KEY (policy_id) REFERENCES policies (id)
);

CREATE TABLE ai_decisions (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id           NUMBER NOT NULL,
    recommendation      VARCHAR2(40) NOT NULL,
    reasoning           VARCHAR2(2000),
    predicted_success   NUMBER(3),
    status              VARCHAR2(20),
    created_at          TIMESTAMP,
    CONSTRAINT fk_ai_decisions_policy FOREIGN KEY (policy_id) REFERENCES policies (id)
);

CREATE INDEX idx_policies_risk ON policies (risk_score);
CREATE INDEX idx_policies_status ON policies (status);
CREATE INDEX idx_policies_due ON policies (due_date);

